# Generated by Django 5.1.dev20231228095837 on 2024-01-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_name', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('price', models.FloatField(default=120)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('seats_available', models.IntegerField(default=100)),
                ('running_days', models.CharField(max_length=50)),
            ],
        ),
    ]
